project:
  type: website

website:
  title: "**Jake Chastney's Academic Homepage**"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: events.qmd
        text: Events
      - href: blog.qmd
        text: Blog
  sidebar:
    style: "docked"
    logo: "./images/user_image.png"
    search: true
    collapse-level: 2
    contents:
      - icon: github
        text: Github
        url: https://github.com/IntelligentSystemsLaboratory
      - icon: twitter
        text: Twitter
        url: https://twitter.com/Bristol_AI_CDT
      - icon: envelope
        text: "Email"
        url: mailto:ck22122@bristol.ac.uk
      - text: "Google Scholar"
        url: https://scholar.google.com/citations?user=<google-scholar-user>
      - text: Pro-AI CDT
        url: https://www.bristol.ac.uk/cdt/practice-oriented-ai/
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



